# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ia_Pqn2NyAPxz2RjOsqxpwnXE5Yx8CBs
"""

!pip install -q -U google-genai pyTelegramBotAPI

import time
import threading
from contextlib import contextmanager
import telebot
from telebot import types
from google import genai

API_KEYS = [
    "AQ.Ab8RN6LX9z04sVW3HVDerzpXMcR37U3m0q5uWF-v5z2ZmWjx8w",
    "AQ.Ab8RN6IhUeNpNm2wB1Y3Cl6AV3X6JYwOl5MZDPdDkGqt7hTc0A",
    "AQ.Ab8RN6Kb6PZaSfFbb_BAsgmK7Qq6zZFX8NbsE3MF_yZmhpflgA",
    "AQ.Ab8RN6IcoekXMQog4C0jknLsIrFakqaI5GXM7ccS0ydPKe06wg",
    "AQ.Ab8RN6J06Lg6Ih2jFlKBqPiXlpoMVfPLn_TeForLQcw-U-7rlg",
    "AQ.Ab8RN6Kw3G0TwqdTWl3UppCfAq7mOvCl2ec0ObfsN6yyqzHv1g",
    "AQ.Ab8RN6KeteVn-Juq30AoSiK90g8XdQDjNTNMuYLxaK6Pe9gEOA",
    "AQ.Ab8RN6IaqFmSJj7_RuHu3MZwF0ZmJuc1hw8OxptOvznetnJUvQ",
    "AQ.Ab8RN6JnGCaijfDn4gckqLS0GFb0cvstK5BBlWkQ_QCVVzFH8A",
    "AQ.Ab8RN6KJNtUM6O3weD7Wkq4MzejCTKmRTtPns6Wb_v8UOUz2_g",
    "AQ.Ab8RN6JT8EtgnmKLYhrhbLHDAGrO6bBSciIyW1L1VVhZX5znMA",
    "AQ.Ab8RN6JOhTSErC4oTIiUgXS_fvNFhoDzhkGhffHiLGKKLu6YGQ",
    "AQ.Ab8RN6Jw0fMi9CaRGcq40vLa6lm8vtkZFB4GP1-BM4vwq8t4vA",
    "AQ.Ab8RN6K46ktEMIJkgE9KDJeOgLA9_s2SFdBuyXXYugNNwmNjmg",
    "AQ.Ab8RN6IGx8YNMQ4AMSe9iLTfw2WkqtQtoV4R-CQLRZfiOmwJSQ",
    "AQ.Ab8RN6LGLWlodGa46_XnRG_KKK7nt47Ljl70mtNVhSBuo8pBoA",
    "AQ.Ab8RN6LqN0hiCQlrI1JMqgAMG1eYR4KfC5zjNtgZDguysUrPlQ",
    "AQ.Ab8RN6IAjiQlmNCqWO7-UEGX3m0WpVyDphbsuS6PC9W0vjHICw",
]

ai_clients = [genai.Client(api_key=k, http_options={'timeout': 60000}) for k in API_KEYS]
current_key_index = 0
key_lock = threading.Lock()

def generate_with_gemini_rotation(prompt: str):
    global current_key_index
    attempts = len(ai_clients)

    for _ in range(attempts):
        with key_lock:
            client = ai_clients[current_key_index]
            idx = current_key_index

        try:
            response = client.models.generate_content(
                model="gemini-3.6-flash",
                contents=prompt
            )
            return response.text
        except Exception as e:
            err_str = str(e).lower()
            print(f"[Ключ #{idx}] Ошибка: {e}")

            retry_triggers = [
                "429", "503", "504", "quota", "exhausted",
                "deadline", "timeout", "unavailable", "resource_exhausted"
            ]

            if any(trigger in err_str for trigger in retry_triggers):
                with key_lock:
                    current_key_index = (current_key_index + 1) % len(ai_clients)
                    print(f"-> Переключаемся на ключ #{current_key_index}...")
                time.sleep(1)
                continue
            else:
                with key_lock:
                    current_key_index = (current_key_index + 1) % len(ai_clients)
                continue

    raise RuntimeError("Все доступные API-ключи Gemini исчерпали свой суточный лимит!")

TELEGRAM_TOKEN = "8831323359:AAH30ojMJVh7Be2ej_iyFGkAjnFyXNo2USA"
bot = telebot.TeleBot(TELEGRAM_TOKEN)

OPERATOR_CHAT_ID = 7872487518

failed_attempts = {}
operator_active = {}
msg_to_client = {}
last_client_id = None
answered_feedbacks = set()
last_ai_response = {}

try:
    bot.remove_webhook()
except Exception:
    pass

@contextmanager
def keep_typing(chat_id):
    stop_event = threading.Event()

    def _loop():
        while not stop_event.is_set():
            try:
                bot.send_chat_action(chat_id, "typing")
            except Exception:
                pass
            stop_event.wait(4)

    thread = threading.Thread(target=_loop, daemon=True)
    thread.start()
    try:
        yield
    finally:
        stop_event.set()
        thread.join(timeout=1)

def get_feedback_keyboard(with_points=True):
    keyboard = types.InlineKeyboardMarkup(row_width=6)
    btn_yes = types.InlineKeyboardButton(text="Помогло", callback_data="help_yes")
    btn_no = types.InlineKeyboardButton(text="Не помогло", callback_data="help_no")
    keyboard.row(btn_yes, btn_no)

    if with_points:
        point_buttons = [types.InlineKeyboardButton(text=str(i), callback_data=f"detail_{i}") for i in range(1, 7)]
        keyboard.add(*point_buttons)

    return keyboard

def get_detail_feedback_keyboard():
    keyboard = types.InlineKeyboardMarkup(row_width=2)
    btn_yes = types.InlineKeyboardButton(text="Помогло", callback_data="help_yes")
    btn_no = types.InlineKeyboardButton(text="Не помогло", callback_data="help_no")
    btn_back = types.InlineKeyboardButton(text="⬅️ Назад", callback_data="go_back")
    keyboard.row(btn_yes, btn_no)
    keyboard.row(btn_back)
    return keyboard

def get_rating_keyboard():
    keyboard = types.InlineKeyboardMarkup(row_width=5)
    stars = [types.InlineKeyboardButton(text=f"{i} ⭐", callback_data=f"rate_{i}") for i in range(1, 6)]
    keyboard.add(*stars)
    return keyboard

def get_restart_keyboard():
    keyboard = types.ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)
    keyboard.add(types.KeyboardButton(text="🔄 Перезапустить бота"))
    return keyboard

@bot.message_handler(commands=['start'])
@bot.message_handler(func=lambda msg: msg.text == "🔄 Перезапустить бота")
def start_cmd(message):
    user_id = message.chat.id
    failed_attempts[user_id] = 0
    operator_active[user_id] = False
    last_ai_response.pop(user_id, None)
    print(f"Команда /start от {user_id}")
    bot.reply_to(
        message,
        "Здравствуйте, пожалуйста подробно опишите вашу проблему.",
        reply_markup=types.ReplyKeyboardRemove()
    )

@bot.message_handler(commands=['close'])
def close_dialog(message):
    global last_client_id
    if message.chat.id == OPERATOR_CHAT_ID and last_client_id:
        client_to_close = last_client_id
        operator_active[client_to_close] = False
        failed_attempts[client_to_close] = 0
        last_ai_response.pop(client_to_close, None)

        bot.send_message(client_to_close, "Диалог с оператором завершен.")
        bot.send_message(
            client_to_close,
            "Пожалуйста, оцените качество работы поддержки по 5-балльной шкале:",
            reply_markup=get_rating_keyboard()
        )

        bot.reply_to(message, "Диалог закрыт.")
        print(f"Оператор закрыл диалог с {client_to_close}")
        last_client_id = None

@bot.message_handler(func=lambda msg: msg.chat.id == OPERATOR_CHAT_ID and msg.reply_to_message is not None)
def handle_operator_reply(message):
    global last_client_id
    replied_msg_id = message.reply_to_message.message_id
    target_user_id = msg_to_client.get(replied_msg_id, last_client_id)

    if target_user_id:
        bot.send_message(target_user_id, message.text)
        bot.reply_to(message, "✓ Доставлено клиенту")
        print(f"Ответ оператора доставлен пользователю {target_user_id}")
    else:
        bot.reply_to(message, "Не удалось найти адресата.")

@bot.message_handler(func=lambda msg: True)
def handle_message(message):
    user_id = message.chat.id

    if user_id == OPERATOR_CHAT_ID:
        return

    if operator_active.get(user_id, False):
        print("Пересылаю сообщение оператору...")
        forwarded = bot.forward_message(OPERATOR_CHAT_ID, user_id, message.message_id)
        msg_to_client[forwarded.message_id] = user_id
        return

    try:
        prompt = (
            "Ты специалист техподдержки ТПУ отвечаешь на вопросы студентов программы Top IT. "
            "В начале напиши: 'Мы поняли, что ваша проблема связана с темой: {категория} . Предлагаем следующее решение: '\n"
            "В самом конце напиши: 'Если у вас возникли трудности на одном из шагов решения, укажите пожалуйста номер шага.'\n"
            "Определи, к какой категории относится вопрос: расписание, учебная программа, Top IT, исправление оценок, приветствие, "
            "Инфраструктура разработки, Проектная деятельность и Хакатоны, Образовательные треки и Элективы, "
            "Сетевая инфраструктура (Wi-Fi и VPN), Учетные записи и Доступы (SSO), Коворкинги и Железо, БРС (Баллы) и Стипендии.\n"
            "Если категория 'приветствие', напиши строго: 'Привет!'\n"
            "Если запрос не подходит ни под одну категорию, ответь строго: 'Извините, данный вопрос не в моей компетенции'.\n"
            "Не запрашивай картинки, стикеры и гифки.\n"
            "Использовать ты можешь только эти ссылки: https://ro-rasp.tpu.ru/ https://stud.lms.tpu.ru/ https://lk.tpu.ru/ https://exam.tpu.ru/exam\n"
            "Если подходит — дай ответ как инструкция по пронумерованным пунктам, их должно быть ровно 6.\n\n"
            f"Вопрос пользователя: {message.text}"
        )
        print("Отправляю запрос в Gemini...")

        with keep_typing(user_id):
            response_text = generate_with_gemini_rotation(prompt)

        print("Ответ от Gemini получен!")
        last_ai_response[user_id] = response_text

        is_competent = "Извините, данный вопрос не в моей компетенции" not in response_text and response_text.strip() != "Привет!"
        bot.reply_to(message, response_text, reply_markup=get_feedback_keyboard(with_points=is_competent))
    except Exception as e:
        print(f"Ошибка при запросе к Gemini: {e}")
        bot.reply_to(message, "Извините, сейчас сервис перегружен или лимит исчерпан. Попробуйте позже.")

@bot.callback_query_handler(func=lambda call: call.data in ["help_yes", "help_no"])
def handle_feedback(call):
    global last_client_id
    user_id = call.message.chat.id
    msg_id = call.message.message_id

    if msg_id in answered_feedbacks:
        bot.answer_callback_query(call.id, text="Вы уже выбрали действие для этого ответа.")
        return

    answered_feedbacks.add(msg_id)
    bot.answer_callback_query(call.id)

    try:
        bot.edit_message_reply_markup(chat_id=user_id, message_id=msg_id, reply_markup=None)
    except Exception:
        pass

    if call.data == "help_yes":
        failed_attempts[user_id] = 0
        last_ai_response.pop(user_id, None)
        bot.send_message(
            user_id,
            "Рады были помочь! Пожалуйста, оцените работу бота по 5-балльной шкале:",
            reply_markup=get_rating_keyboard()
        )

    elif call.data == "help_no":
        last_ai_response.pop(user_id, None)
        failed_attempts[user_id] = failed_attempts.get(user_id, 0) + 1
        count = failed_attempts[user_id]
        print(f"Попыток 'не помогло' для {user_id}: {count}")

        if count >= 2:
            operator_active[user_id] = True
            last_client_id = user_id
            bot.send_message(user_id, "В ближайшие время с вами свяжется специалист")
            alert = bot.send_message(
                OPERATOR_CHAT_ID,
                f"Клиент {user_id} переведен на оператора!\nОтветьте через Reply на это сообщение."
            )
            msg_to_client[alert.message_id] = user_id
        else:
            bot.send_message(user_id, "Пожалуйста, опишите проблему подробнее, для того чтобы мы могли эффективно разобраться")

@bot.callback_query_handler(func=lambda call: call.data == "go_back")
def handle_go_back(call):
    user_id = call.message.chat.id
    bot.answer_callback_query(call.id)

    try:
        bot.edit_message_reply_markup(chat_id=user_id, message_id=call.message.message_id, reply_markup=None)
    except Exception:
        pass

    saved_response = last_ai_response.get(user_id)
    if not saved_response:
        bot.send_message(user_id, "Контекст предыдущего ответа не найден. Пожалуйста, опишите проблему заново.")
        return

    is_competent = "Извините, данный вопрос не в моей компетенции" not in saved_response and saved_response.strip() != "Привет!"
    bot.send_message(
        user_id,
        f"Возвращаемся к основному ответу:\n\n{saved_response}",
        reply_markup=get_feedback_keyboard(with_points=is_competent)
    )

@bot.callback_query_handler(func=lambda call: call.data.startswith("rate_"))
def handle_rating(call):
    user_id = call.message.chat.id
    rating_val = call.data.split("_")[1]
    bot.answer_callback_query(call.id)

    try:
        bot.edit_message_reply_markup(chat_id=user_id, message_id=call.message.message_id, reply_markup=None)
    except Exception:
        pass

    print(f"Оценка от {user_id}: {rating_val} ⭐")
    bot.send_message(
        user_id,
        f"Спасибо за оценку ({rating_val} ⭐)!\nЧтобы начать новый диалог, нажмите кнопку ниже.",
        reply_markup=get_restart_keyboard()
    )

@bot.callback_query_handler(func=lambda call: call.data.startswith("detail_"))
def handle_detail_choice(call):
    user_id = call.message.chat.id
    point_num = call.data.split("_")[1]
    bot.answer_callback_query(call.id)

    try:
        bot.edit_message_reply_markup(chat_id=user_id, message_id=call.message.message_id, reply_markup=None)
    except Exception:
        pass

    saved_response = last_ai_response.get(user_id)
    if not saved_response:
        bot.send_message(user_id, "Контекст ответа не найден. Пожалуйста, задайте вопрос заново.")
        return

    detail_prompt = (
        "Ты специалист техподдержки ТПУ отвечаешь на вопросы студентов программы Top IT. "
        "Отвечай кратко и по делу. "
        "Никаких '*'. "
        "Не запрашивай картинки, стикеры и гифки. "
        "Использовать ты можешь только эти ссылки: https://ro-rasp.tpu.ru/ https://stud.lms.tpu.ru/ https://lk.tpu.ru/ https://exam.tpu.ru/exam "
        "Если подходит — дай ответ как инструкция по пронумерованным пунктам.\n\n"
        f"Контекст предыдущего ответа:\n{saved_response}\n\n"
        f"Запрос: Расскажи подробнее пункт {point_num}"
    )

    try:
        with keep_typing(user_id):
            response_text = generate_with_gemini_rotation(detail_prompt)

        bot.send_message(user_id, response_text, reply_markup=get_detail_feedback_keyboard())
    except Exception as e:
        print(f"Ошибка Gemini при детализации: {e}")
        bot.send_message(user_id, "Извините, возникла ошибка при формировании подробного ответа. Попробуйте еще раз.")

print("Бот успешно запущен и слушает события...")

while True:
    try:
        bot.infinity_polling(
            timeout=10,
            long_polling_timeout=15,
            skip_pending=True,
            logger_level=None
        )
    except KeyboardInterrupt:
        print("\nБот остановлен пользователем.")
        break
    except Exception as err:
        print(f"Сетевой сбой ({err}). Переподключение через 3 секунды...")
        time.sleep(3)

